### ISSUE TITLE
Screenshot not shown in embedded docs

### ISSUE THREAD

**Issue by sciencewhiz** [Mechanical-Advantage/AdvantageScope#104]
**Describe the bug**
In AdvantageScope docs on Windows from WPILib build (beta 4), the example screenshot doesn't show

**To Reproduce**

1. Click on 📖

**Expected behavior**
Example AdvantageScope screenshot should be shown

**Screenshots**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/4885091/726c625a-c6c1-4194-bd0b-cf4794084d75)

**Version (required):**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/4885091/6792bc77-3280-4f6a-966a-24b465d8d313)

**Comment by sciencewhiz** [comment]
After loading AdvantageScope a second time, the screeenshot loaded

**Comment by jwbonner** [comment]
This should be fixed now. It looks like there was an edge case on startup where the renderer didn't always receive the platform information before trying to set up image URLs.
