### ISSUE TITLE
Missing Trajectory Segments

### ISSUE THREAD

**Issue by Nsl106** [Mechanical-Advantage/AdvantageScope#105]
**Describe the bug**
When viewing trajectories in the 3D field, additional segments are not added above the number that it starts with when connecting to the simulation unless refreshed. I don't know if this has to do with having trajectories with very few points (usually 3-4) or if it has to do with something else. After refreshing (changing the display to something else, then back to a trajectory), it works. Not sure if I have explained this well, so I'll attach a video to clarify :)

**To Reproduce**
see above

**Expected behavior**
I would expect it to render all the segments every time without needing to refresh it.

**Screenshots**
https://github.com/Mechanical-Advantage/AdvantageScope/assets/87742096/b6fe8033-3e4b-462f-9594-c9f052e41ed3

**Version (required):**
It wouldn't let me select in that menu, but here's a screenshot
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/87742096/3076b22b-df00-4e72-bc3b-4b4f7bbb088b)

**Additional context**
Here's the link to our code if it helps: https://github.com/Team-8-bit/robotbase/tree/f68c7960b3703a9e37becd6eabbf622089097fe4
The trajectory in question is shown under AdvantageKit/RealOutputs/Planner/Path when the robot is enabled, and you can move it using generic swerve controls from joystick 0

**Comment by jwbonner** [comment]
Thanks for finding this. I've been fighting bugs with line rendering on the 3D field for a while (it's related to strange behavior with low-level buffer allocations in three.js). I fixed a bunch of bugs before the 2024 betas, but apparently I missed this one. It should be fixed now.
