### ISSUE TITLE
Update Line Graph Values

### ISSUE THREAD

**Issue by tssmith7** [Mechanical-Advantage/AdvantageScope#106]
It would be nice if the line graph values in the lower "Left Axis", "Discrete Fields", and "Right Axis" panes updated their values as the cursor runs across the graph not just when playing back the Log file or clicking on a certain spot in the time history.

**Comment by jwbonner** [comment]
Thanks for the suggestion, this now matches the behavior when hovering on the line graph alongside a second window.
