### ISSUE TITLE
Some way to easily view multiple numeric values

### ISSUE THREAD

**Issue by lobsterwise** [Mechanical-Advantage/AdvantageScope#107]
When doing things like calibrating swerve modules, it's helpful to be able to see multiple live numbers at once. However, AdvantageScope doesn't have an easy way to do this. The list of plotted values on the line graph is too small to see more than a few numbers at once. 

Maybe a Shuffleboard-like tab would work. Or show the value next to the NT key on the left pane.

**Comment by jwbonner** [comment]
For the next release, values for most fields will be displayed in the sidebar as shown below. It sounds like this addresses the issue.

<img width="580" alt="Screenshot 2023-11-30 at 11 25 47 PM" src="https://github.com/Mechanical-Advantage/AdvantageScope/assets/47046556/8cec2663-2604-4aa3-8515-f5f675e68969">
