### ISSUE TITLE
Add Driver Station POVs to 3d Field

### ISSUE THREAD

**Issue by scarmain** [Mechanical-Advantage/AdvantageScope#108]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I found when right clicking on the 3d field, it gives you a list of the camera options (orbit, robot POV, and any cameras on the model).  Could there be another selection for driver POV behind the glass?  

It could have all the selectors (Red 1 - Blue 3), but maybe an auto could be added also to read the DS info and get alliance and station data and select the right driver station.

**Describe alternatives you've considered**
none

**Additional context**
Like this: 
![2023-11-21](https://github.com/Mechanical-Advantage/AdvantageScope/assets/11251907/e1b60922-e22d-42a4-893f-6db7298ddbb1)

**Comment by jwbonner** [comment]
Thanks for the suggestion, this is now implemented. There are options for each Driver Station and an "auto" option that uses the data from the log file.
