### ISSUE TITLE
A way to see events

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#115]
**Is your feature request related to a problem? Please describe.**
It's hard sometimes to understand when important events happened. For example, the motor's current got to zero because it hit a limit switch, but there's no easy way to see this and correlate between these two events.

**Describe the solution you'd like**
I was imagining something like a logging function in AdvantageKit that receives a logging message, severity level, and an optional JSON metadata field (could be a `Map` object) used for filtering or custom purposes (log type like "command started", "sensors" type; subsystem name, etc). Then you can see the events as you hover over the line graph or as lines inserted in the table view. Regarding the graph, I thought of something like in this [screenshot](https://github.com/Mechanical-Advantage/AdvantageScope/raw/main/docs/resources/line-graph/line-graph-1.png) -- events would be shown as dashed lines, similar to the timestamp, and when hovered would show the full message. A window to filter based on the aforementioned JSON will also be available.  
Something else that could be useful is attaching logs to subtables, so only when values from the relevant suitable are used will the associated events be shown.

**Comment by jwbonner** [comment]
For the example you gave, you can log the value of the limit switch as a boolean on the line graph and show it as a discrete field. In general, events and state changes can be expressed as discrete fields (booleans, strings, etc). Does this cover your use case?

**Comment by katzuv** [comment]
Can strings be shown on the graph?

**Comment by jwbonner** [comment]
Yes, you can drag then to "discrete fields"

**Comment by katzuv** [comment]
Oh, that's nice! Didn't know about that. That seems as a good solution for what I was looking for, thanks.
The filtering feature might still be useful.

**Comment by jwbonner** [comment]
I'm not sure what you mean by "filtering." Fields are already organized by table, and you can easily toggle the visibility of each field on the graph.

**Comment by katzuv** [comment]
For example, a team logs every second some string with state for each subsystem, but it's being logged to the same key. The team can add `{"subsystem": "elevator"}`/`{"subsystem": "drivetrain"}`, etc. to the string metadata, then filter only "elevator" state logs.

**Comment by jwbonner** [comment]
In that case, the states of different subsystems should probably be logged to different keys. That could also keep them organized into tables.

**Comment by katzuv** [comment]
That sounds reasonable. Thanks!
