### ISSUE TITLE
Auto scroll should be disabled when scrolling up in table/console views

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#116]

**Comment by jwbonner** [comment]
This should already be supported for the line graph. Are you having issues making it work?

It’s not currently supported for the table and console, but that seems like a reasonable addition.

**Comment by katzuv** [comment]
So I was not sure about the graph but included it just in case it wasn't implemented already.

**Comment by jwbonner** [comment]
Thanks for the suggestion, this is now implemented for the table in addition to the line graph.
