### ISSUE TITLE
Enable keyboard navigation in keys search results and abbreviation search

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#117]
It'd be nice to be able to navigate the keys search results menu with up/down keys. Also, abbreviation search might be useful. Not sure if that is the technical term, but that's what I mean:
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/31829093/ab612b04-7371-4191-a075-984efd2d1de4)
It can also be more reserved as IntelliJ IDEA does that -- only prefixes of words are accepted (hence the "e" at the end will make no results shown).

**Comment by jwbonner** [comment]
Currently, the search looks for any key where the search text appears. Is this different than your suggestion to match the IntelliJ behavior?

**Comment by katzuv** [comment]
Yes, for example for the field "Auto Chocies", IntelliJ IDEA will match `ac` `auch` too (`Au`to `Ch`oices).

**Comment by 12Jeef** [comment]
I suggest [FuseJS](https://www.fusejs.io/) for abbreviation search.

**Comment by jwbonner** [comment]
Both of these features are now implemented. You can use the keyboard (up, down, enter) to navigate through the search results, and it uses FuseJS as the backend so the search term doesn't need to appear identically in the key.
