### ISSUE TITLE
Previewed strings should fill available space

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#118]
Strings are truncated even if there's plenty of space:
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/31829093/e189ab65-331d-4d57-82b9-1b0adca74e1b)

**Comment by jwbonner** [comment]
This is intentional to avoid cluttering the sidebar, since filling it with too much text makes it harder to view and navigate at a glance. I think longer strings are best viewed with the table, console, or line graph (especially with the example of AdvantageKit's console logging).

**Comment by katzuv** [comment]
I see. Perhaps then the shown length should be in some range depending on the width? So it will be 8 at the minimum but say 15 top if the sidebar is wide. But this is something that is down to personal preference too.

**Comment by jwbonner** [comment]
Since the purpose of the sidebar is just to preview the value, I'm not sure there's a compelling reason to show more of the text. Thanks for the suggestion though.

**Comment by jwbonner** [comment]
Having gotten this suggestion again with #138, I experimented with changing the value length based on the sidebar width and I think it works reasonably well without causing too much clutter. Thanks for making the suggestion originally.
