### ISSUE TITLE
Different coordinate system/origin options for Points tab

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageScope#119]
**Is your feature request related to a problem? Please describe.**
The points tab currently only supports a single coordinate system (+X right, +Y down) with the origin in the top left corner. This makes it more difficult to display data from different coordinate systems, or data relative to a central origin without first transforming the data to be compatible with the points tab.

**Describe the solution you'd like**
Add options to the points tab that will allow the user to switch between different coordinate systems, as well as an option to set the location of the origin. For example:

Coordinate System Options:
* +X right, +Y down
* +X right, +Y up
* +X up, +Y left

Origin Options:
* Top Left
* Top Right
* Bottom Left
* Bottom Right
* Center

Less important of a request, but still in line with improvements to the Points tab, would be allowing the use of a single topic to define 2d points, similar to how it works in the 3d field tab. This could allow either a double array where every 2 points define an X and Y coordinate, or an array of Translation2d structs.

**Additional context**
We have been experimenting with using 2d lidar scan data, and the Points tab seems like an excellent way to display the current scan. However, we currently need to publish scan data twice: once in a WPILib compatible coordinate system, and once in a Points tab compatible coordinate system with an offset applied to center it.

**Comment by jwbonner** [comment]
Thanks for the suggestion. This is now implemented, with dropdowns to choose the coordinate system and a separate entry for "Combined" data (either a single array of XY coordinates or a `Translation2d` array). You can see the updated docs [here](https://github.com/Mechanical-Advantage/AdvantageScope/blob/main/docs/tabs/POINTS.md).
