### ISSUE TITLE
 Allow the WPILib Installer to update AdvantageKit on macOS

### ISSUE THREAD

**Issue by ThadHouse** [Mechanical-Advantage/AdvantageScope#123]
Changes in macOS Ventura make it so updating apps from other apps is blocked by default. AdvantageKit is the first app WPILib has installed, and its going to have trouble updating in the next release due to this. The solution is to specify in the AdvantageKit plist that it's allowed to be updated by the WPILib Team ID.

https://developer.apple.com/documentation/bundleresources/information_property_list/nsupdatesecuritypolicy

**Comment by ThadHouse** [comment]
That fix isn't going to work @jwbonner. We're not marked as an installer, so it needs to be using AllowProcesses

**Comment by jwbonner** [comment]
This is using the WPILib team ID. The format for `AllowedProcesses` appears to be correct now based on the examples in the Apple article.
