### ISSUE TITLE
Underscores in NT keys are interpreted as slashes in tree view

### ISSUE THREAD

**Issue by shueja** [Mechanical-Advantage/AdvantageScope#124]
**Describe the bug**
In the 2024.1.1 wpilib-packaged AdvantageScope version, `_` in an NT key is interpreted as a path separator.

**To Reproduce**

1. In OutlineViewer, start it in server mode and add `m_test/value` (type doesn't matter)
2. Connect to the local server from AdvantageScope
3. See the tree shown as `m/test/value`

**Expected behavior**
NT Tree view should allow underscores in keys without interpreting them as path separators.

**Screenshots**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/d9e297ae-794c-49ff-836e-6672e33b8dde)
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/3930216a-cc04-4f3f-a44b-3211692fe7ab)

With the reproduction steps above:
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/595296f9-9767-474f-9ef4-b4f3ec01cfc2)
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/00efa276-d362-4496-bbad-66fd34e3acbd)

**Version (required):**
(The text in "About Advantagescope" isn't selectable or copyable)
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/cc69505c-b03a-437d-9817-3ea20902bae2)

**Comment by shueja** [comment]
As the Monologue author, I can also add a flag that strips the `m_` and `k_` out of field names, but that's more of a convenience thing for Monologue users specifically.

**Comment by jwbonner** [comment]
Adding exceptions for `m_` and `k_` on the AdvantageScope side seems reasonable, since I think it's pretty unambiguous in an FRC context that those are just prefixes. Obviously if you think it's useful to be able to strip them out in Monologue you could add that too.

**Comment by caburum** [comment]
We use underscores in our variable names for units (like `wheelVelocity_mps`) and this has caused all of our logged variables to be harder to access. If lacking a convention in other log formats is a problem, perhaps only use slashes for the AdvantageKit and SmartDashboard/Shuffleboard sections.

**Comment by jwbonner** [comment]
It looks like the only real example that doesn't follow the convention of `/` and `:` for separators is CTRE's signal names. In particular, the current approach may be problematic for Python teams that stick with snake case for field names. While it's frustrating to need special cases like this, it seems like the safer way forward is to handle CTRE's signals separately and default to not separating on underscores.

**Comment by jwbonner** [comment]
That update should address all of the use cases correctly. By default, keys are only separated on `/` and `:`. Anything from a Phoenix source (where the key starts with "Phoenix6") will be separated on `/`, `:`, and `_`. Thanks for the feedback everyone.
