### ISSUE TITLE
"About Advantagescope" window does not have selectable/copyable text

### ISSUE THREAD

**Issue by shueja** [Mechanical-Advantage/AdvantageScope#125]
**Describe the bug**
See title.

**To Reproduce**

1. Open AdvantageScope (on Windows)
2. Click on "Help->About AdvantageScope"
3. Try to copy the text

**Expected behavior**
Able to select and copy the text there. Either allow selection or add a button that copies the contents to clipboard (or both).

**Version (required):**
Copy the contents of the "About AdvantageScope" window and paste it here. On Windows/Linux, click "Help" > "About AdvantageScope". On macOS, click "AdvantageScope" > "About AdvantageScope" in the menu bar.

... this is why this is an issue.
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/32416547/bf8463ba-82ef-4a77-bd12-6a19de08a1c4)

**Comment by jwbonner** [comment]
A button to copy it to the clipboard seems like a good solution. When writing the template I only tried it on macOS, which lets you copy text from native popup windows.

**Comment by jwbonner** [comment]
There is now a support for copying the text to the clipboard, which should work on all operating systems. Thanks for the suggestion.
