### ISSUE TITLE
Sidebar not showing all network tables entries

### ISSUE THREAD

**Issue by blaine141** [Mechanical-Advantage/AdvantageScope#127]
**Describe the bug**
I can not get 3d poses to show up on the left when following the "3D Field" tutorial.

**To Reproduce**
Follow the instructions listed in 3D Field to publish Pose3d objects. Both the array and single Pose 3D. They will not show up on the sidebar to select

**Expected behavior**
The NetworkTables entries appear on the left

**Screenshots**
Network Tables entries
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/6363539/43a6df4b-2627-426a-b357-2f5e89ea7cb3)

No corresponding sidebar entries.
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/6363539/254cd602-3203-4b1b-8853-5d06f74a9632)

**Version (required):**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/6363539/88e3e30f-917f-4405-a2f2-e156cca1791d)

**Additional context**
Maybe it is related to the struct type? I have a Field2d showing up correctly. I am also running from a simulator

**Comment by jwbonner** [comment]
Are you publishing the fields without a leading `/`? In the latest released version a leading slash is required for NT entries, though I just pushed a fix for that (12afa312baba019aa4ca15484459dc5d3cc6c489). It's definitely misleading that the examples in the docs don't include that.

Let me know if that seems to explain the issue, otherwise I can do some more digging.

**Comment by blaine141** [comment]
Dude!!!! It worked!!! I was reverse engineering your code and using the developer console debugger. I would have never found that. 

Is the leading slash a NT standard? If so I can make a PR for the docs.

**Comment by jwbonner** [comment]
The leading slash isn't required by NT, so the fix I pushed should make it work properly without that. That should take care of the issue with the docs, but thanks for the offer.

**Comment by blaine141** [comment]
BTW, this tool is amazing! This is the best-designed solution I have ever seen introduced into FRC. I really hope everyone starts using this tool so we can see some cool auton and less bugs!
