### ISSUE TITLE
Add option to choose path of custom assets directory

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#133]
Currently the custom assets directory path is fixed. It'll be nice to be able to choose the directory from which assets would be loaded, e.g. the robot code directory (similar to PathPlanner's "Open Robot Project" functionality). The main advantage is that assets can be managed in Git without needing to copy them to another directory.

**Comment by jwbonner** [comment]
Thanks for the suggestion. You can now select a custom folder using a new option directly under the "Show Assets Folder" button, which will persist when the app restarts.
