### ISSUE TITLE
Error popup when custom asset JSON file is empty or in wrong format

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#134]
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/31829093/e98750fd-413d-4c6c-8950-26413a9764d8)

The error popup keeps popping up, a nice enhancement would be to catch this exception and show a friendlier message to the user.

**Comment by jwbonner** [comment]
That update should address the issue. JSON parsing issues are correctly caught, and any asset loading failure (regardless of cause) will produce a popup with details available in the developer console.
