### ISSUE TITLE
Step through log with arrow keys

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageScope#142]
**Is your feature request related to a problem? Please describe.**
To the best of my knowledge, the only way to look at a specific point in time in a log is to scrub through it with the mouse in the timeline at the top of the window. This can be pretty imprecise, and depending on the length of the log, might not have high enough resolution to get to the exact point in time you want to look at.

**Describe the solution you'd like**
I propose being able to use the arrow keys to step through the log file one time step at a time (likely 0.02s to correspond with the robot's loop time) similarly to stepping through a video frame by frame.

**Comment by jwbonner** [comment]
Thanks for the suggestion. You can now step forward and backward in the log by 20ms using the arrow keys. Based on AdvantageKit's synchronized timestamps, it will step forward and backward by one loop cycle (regardless of timing) when viewing AdvantageKit data.
