### ISSUE TITLE
Create a shortcut to bring all windows to the front

### ISSUE THREAD

**Issue by Gold872** [Mechanical-Advantage/AdvantageScope#143]
The new feature where you can click a button to bring all windows to the front is amazing and I'm a huge fan of it. One thing that would make it even better is if there was a shortcut for it. This would remove the need to have to find the main window and go into the menu to bring everything else to the front.

**Comment by jwbonner** [comment]
Thanks for the suggestion. I mapped it to "Ctrl+B", which is otherwise unused and near "Ctrl+M" for minimize.
