### ISSUE TITLE
Ability to "merge with DSLog"

### ISSUE THREAD

**Issue by Gold872** [Mechanical-Advantage/AdvantageScope#150]
**Is your feature request related to a problem? Please describe.**
One very useful feature this program has is the ability to open DSLog/DSEvents and merge it with other logs. However, this can be quite challenging at times, since the log files for the driver station and wpilogs are often in different folders.

**Describe the solution you'd like**
I have 2 ideas, one simple, and one not. The simple idea is to have a button similar to the "Open Multiple", but it allows you to open a DS file and have it merge with the currently loaded file instead of unloading it. This would be incredibly useful when debugging, as you would be able to view internal code variables along with things only the driver station logs, such as packet loss, latency, RIO CPU info, etc.

The more complicated idea is to automatically search the user's DS log directory for the driver station log(s) that match up to the times in the WPILog. Not sure how feasible this is but it would be really cool to have if it's possible.

**Describe alternatives you've considered**
The DS log viewer is good, but it's very hard to read and the UX is not great. Plus, you can't view data from code logged variables.

**Comment by jwbonner** [comment]
Closed by https://github.com/Mechanical-Advantage/AdvantageScope/pull/192, partially deferred to #192.
