### ISSUE TITLE
3d Field Not Rendering on Arch Linux.

### ISSUE THREAD

**Issue by person4268** [Mechanical-Advantage/AdvantageScope#157]
**Describe the bug**
Since some advantagescope version that I unfortunately do not remember, the 3d field does not render properly, and is just blank. The flatpak version of advantagescope I can verify works perfectly fine.

**To Reproduce**
1. Open the 3d field.
2. Observe nonfunctionality

**Expected behavior**

**Screenshots**
![image](https://github.com/Mechanical-Advantage/AdvantageScope/assets/28717044/bd3765fd-4497-4772-bfc7-2b1dceb639ca)

**Version (required):**
```
Version: 3.2.1
Distributor: FRC 6328
Platform: linux-x64
Build Date: 3/13/2024, 22:18:14 UTC
Electron: 26.2.1
Chromium: 116.0.5845.188
Node: 18.16.1
```

**Additional context**

**Comment by goatfanboi23** [comment]
This is a known problem with Nvidia GPUs (on Wayland) and electron based apps. A workaround for now is to launch advantage scope with the "--use-gl=desktop" flag. This will most likely result in lag because it uses the CPU however a laggy field is better than no field.

**Comment by person4268** [comment]
This isn't an issue for me anymore as of 4.0.0-beta-2
