### ISSUE TITLE
Option to merge or unload current log when opening a new log

### ISSUE THREAD

**Issue by Gold872** [Mechanical-Advantage/AdvantageScope#158]
This is another possible solution to #150, but I think it has a bunch of other applications too. Right now when you either open a log via the menu  or drag and drop, it will unload the one you currently have loaded, and then load the one you just selected. This can be a bit annoying when you want to merge logs that are all in different locations.

**Proposed Solution**
When you open a new log and there's one currently loaded, it should show a popup with 2 options: "Unload Current Log", and "Merge with Current". This has several applications:
1. Exporting data for SysID that uses fields from both robot code and hoot logs
2. Easily comparing data between different match logs
3. Viewing data from DS logs and hoot logs with wpilogs

While right now this is possible, it's not very easy to do since all of the logs you want to merge have to be in one place, this would make log merging much easier to do.

**Comment by jwbonner** [comment]
Closed by https://github.com/Mechanical-Advantage/AdvantageScope/pull/192
