### ISSUE TITLE
Deprecated dependency

### ISSUE THREAD

**Issue by spacey-sooty** [Mechanical-Advantage/AdvantageScope#162]
**Describe the bug**
The subdependency https://www.npmjs.com/package/sourcemap-codec/v/1.4.8 is deprecated. The author recommends using @jridgewell/sourcemap-codec instead.

**Comment by jwbonner** [comment]
This is not used directly, but is several layers down the dependency chain for [rollup-plugin-cleanup](https://www.npmjs.com/package/rollup-plugin-cleanup). While that plugin hasn't been updated for a few years, it serves its purpose without issue. I don't see a compelling reason to change anything at this point.
