### ISSUE TITLE
Line Graph Show Values

### ISSUE THREAD

**Issue by scarmain** [Mechanical-Advantage/AdvantageScope#17]
When you use the line graph tab to view data, you can click to mark a spot for reference.  When you do this click, could you also show the values at this point of time?  I've seen other analysis tools have it when you hover over a line, it has a little popup window to show you the raw values, or another "easy" (don't know your code) way to do this would be at the bottom, where you list the Left/Discrete/Right Axis signals and have the dot for the signal color, add another field there to show the raw value.  (kinda how the Discrete values show you on the graph, but could be in a separate point)

This way we don't have to constant look back at the scale and estimate what the value is, we can just see it at an easy to refer to place.

**Comment by jwbonner** [comment]
Here's the finished product. I found that putting the values in the legend seemed to work best as it avoids cluttering the graph or blocking other information.

https://user-images.githubusercontent.com/47046556/198933646-2597c5a4-9e2b-4541-a8b5-b48a1a5ba150.mp4
