### ISSUE TITLE
2024 Kitbot model wheels going through floor

### ISSUE THREAD

**Issue by DanPeled** [Mechanical-Advantage/AdvantageScope#176]
**Describe the bug**
In the `2024 Field`, together with the `2024 Kitbot` robot model, the robot's drive wheels are going through the floor 

**To Reproduce**

1. Go to `3D Field`
2. Click on `Robot` Dropdown
3. Scroll down to `2024 Kitbot`
4. Rotate to view the model from below to field

**Expected behavior**
The robot's wheels should be below the floor of the field

**Screenshots**
![image](https://github.com/user-attachments/assets/9ff39457-3f52-4ebd-8005-d9f8e1bb3200)

**Version (required):**
Version: 3.2.1
Distributor: WPILib
Platform: linux-x64
Build Date: 3/13/2024, 22:19:40 UTC
Electron: 26.2.1
Chromium: 116.0.5845.188
Node: 18.16.1

**Comment by jwbonner** [comment]
I just uploaded a new KitBot model that fixes this issue. AdvantageScope will download the new model the next time it is launched while connected to the internet.
