### ISSUE TITLE
Custom Tab Names

### ISSUE THREAD

**Issue by scarmain** [Mechanical-Advantage/AdvantageScope#18]
Instead of the plotting tabs saying Line Graph/Table/Odometry, etc, can we change the name of the tabs to reflect what we are looking at (like the wheel currents as one plot, drive data second plot, etc).  I'm even ok if you left the icons, just let us change the name.

**Comment by jonahb55** [comment]
Here's what I came up with. The name is saved with the rest of the tab configuration, so it will persist when you restart the app.

![Advantage Scope - Renaming Tab](https://user-images.githubusercontent.com/47046556/198037357-9874655b-8010-460a-bf64-f2c5503cc45c.gif)
