### ISSUE TITLE
Different April Tag ID 1

### ISSUE THREAD

**Issue by isaacngkh** [Mechanical-Advantage/AdvantageScope#183]
**Describe the bug**
April Tag ID 1 in 3D Field is different than the actual April Tag ID 1

**Screenshots**
![image](https://github.com/user-attachments/assets/8f137705-226f-47ed-ab48-87cceec105f4)

![image](https://github.com/user-attachments/assets/5482bdd1-3229-4002-8058-1bda5001e227)
https://firstfrc.blob.core.windows.net/frc2024/FieldAssets/Apriltag_Images_and_User_Guide.pdf

**Version (required):**
Version: 3.2.1
Distributor: FRC 6328
Platform: win32-x64
Build Date: 3/13/2024, 22:18:14 UTC
Electron: 26.2.1
Chromium: 116.0.5845.188
Node: 18.16.1

**Comment by jwbonner** [comment]
Good catch! This is actually an error in the [Onshape field model](https://cad.onshape.com/documents/dcbe49ce579f6342435bc298/w/b93673f5b2ec9c9bdcfec487/e/6ecb2d6b7590f4d1c820d5e3) that AdvantageScope uses. I've flagged the issue so it shouldn't happen again in the future, but in the meantime you can always manually publish an AprilTag with the correct pose and ID if you need to vision detect that particular tag.
