### ISSUE TITLE
Structs with schemas including types such as int, byte, and long don't deserialize correctly.

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#188]
When connecting to a robot that publishes structured data types with WPILIB structs, they are only collapsable/you can see individual fields if they do not include any datatypes that are not doubles or floats.

1. Create a struct implementation for a data type that includes different types, like ints and bytes.
2. Log them through NT4 or AdvantageKit
3. Notice that you can not see any of the fields of the  serialized data if it includes any whole number types, (int, byte, long, etc)

I expected it to deserialize and show serialized ints and bytes to log data types with whole numbers as fields, however, it shows nothing instead.

P.S. you have a great software overall :3

**Comment by jwbonner** [comment]
What are the type names you're using? Note that `int`, `byte`, and `long` are not valid types under the [struct spec](https://github.com/wpilibsuite/allwpilib/blob/main/wpiutil/doc/struct.adoc#standard-declaration). You probably want to use something like `char`, `int8`, `int32`, or `int64`.

**Comment by blaze-developer** [comment]
Oop- yeah I got it completely wrong. I will try those! I apologize for me being dumb lol

**Comment by blaze-developer** [comment]
I think you may have referenced the wrong issue but oh well

**Comment by jwbonner** [comment]
Yeah, I referenced the issue using the ID in the other repo then transferred it after.
