### ISSUE TITLE
Saving/Sharing Dashboard Setups

### ISSUE THREAD

**Issue by scarmain** [Mechanical-Advantage/AdvantageScope#19]
Can you add an option to allow dashboards (or plot tabs) be saved and shared between computers?  You already have this feature as it remember what tabs you have open the next time you fire up the tool, can this be a publicly used file to share to another computer, import the config, and they can see all the tabs setup already?

**Comment by jwbonner** [comment]
This feature should now be working. It exports a JSON file that can be loaded on other computers.

https://user-images.githubusercontent.com/47046556/198933821-49fb2be6-13dd-437f-b5b6-dac02f2bfe65.mp4
