### ISSUE TITLE
Beta: Maximizing the window removes translucency effects

### ISSUE THREAD

**Issue by Gold856** [Mechanical-Advantage/AdvantageScope#198]
**Describe the bug**
The background is translucent until you maximize the window.

**To Reproduce**

1. Open AdvantageScope.
2. Maximize the window.
3. Note the lack of translucency on the background

**Expected behavior**
I expected that the background would stay translucent after maximizing the window.

**Screenshots**
![image](https://github.com/user-attachments/assets/68c891d2-dd7d-4dda-91fa-2c6218c7d4cd)

**Version (required):**
Version: 4.0.0-beta-1
Distributor: WPILib
Platform: win32-x64
Build Date: 9/26/2024, 24:43:48 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment]
See https://github.com/Mechanical-Advantage/AdvantageScope/issues/197#issuecomment-2395222600
