### ISSUE TITLE
Beta: Opening a log while the window is maximized causes the name to show in the top left

### ISSUE THREAD

**Issue by Gold856** [Mechanical-Advantage/AdvantageScope#199]
**Describe the bug**
Opening a log while AdvantageScope is maximized causes the file name to be overlaid on the top left of the window over the menu buttons.

**To Reproduce**

1. Open AdvantageScope.
2. Maximize the window.
3. Open a log.
4. Notice the overlaid file name in the top left corner.

**Expected behavior**
I expected the top left corner to not change when opening logs.

**Screenshots**
![image](https://github.com/user-attachments/assets/e48fc156-6263-4794-8dac-f7574ed4613b)

**Version (required):**
Version: 4.0.0-beta-1
Distributor: WPILib
Platform: win32-x64
Build Date: 9/26/2024, 24:43:48 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment]
See https://github.com/Mechanical-Advantage/AdvantageScope/issues/197#issuecomment-2395222600
