### ISSUE TITLE
Beta: 3D Field Widget Lagging with Table Widget

### ISSUE THREAD

**Issue by catr1xLiu** [Mechanical-Advantage/AdvantageScope#200]
**Describe the bug**
When using the table view widget and the 3d field widget together, the 3d field widget seems to be lagging.

**To Reproduce**
1.Open any log file
2. Drag some poses to the 3d field widget.  
3. Open the 3d field widget in a sperate window
4. In the main window, switch to "table view" and open some tables
5. If the table is rolling down too fast, the field3d widgets gets extremely laggy.

**Screenshots**
![image](https://github.com/user-attachments/assets/11dbe6b5-56bf-4952-a2c4-f28ef332abd4)

**Version**
Version: 4.0.0-beta-1
Distributor: FRC 6328
Platform: win32-x64
Build Date: 9/26/2024, 24:41:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Aditional Context**
Running on a Windows10 Laptop, with R7-8845HS CPU and 32GB Memory.
There is NO performance issue when running 3d field widget alone.

**Comment by jwbonner** [comment]
It looks like the table tab was a performance bottleneck, which prevented updates to the 3D field. I tracked down the issue and swapped a call from `innerText` to `textContent`, which should be a ~15x performance improvement.
