### ISSUE TITLE
High GPU utilization at idle

### ISSUE THREAD

**Issue by rzblue** [Mechanical-Advantage/AdvantageScope#204]
AdvantageScope 2025 has significant continuous GPU utilization on Windows even when not displaying anything and/or in the background. Screenshot shows 2 AdvantageScope instances running; The top is 2025, the bottom is 2024 (both wpilib packaged versions). Both instances in the screenshot are open side-by-side in the foreground, displaying an empty line graph and nothing else (utilization does not change when in background/not visible).

<img width="842" alt="image" src="https://github.com/user-attachments/assets/3e715484-c17d-4a55-b4de-9907aee80272">

Edit: It actually seems to be related to the current tab- switching to the docs tab drops utilization to near 0. 2025 is still consistently higher than 2024 on tabs that use nonzero gpu.

**Comment by jwbonner** [comment]
There were several tabs (notably the line graph) which supported on-demand rendering in 2024 but I neglected to reimplement when rewriting them. I pushed a fix.

**Comment by rzblue** [comment]
Sweet, that's much better!
