### ISSUE TITLE
App Crashes when Scrolling on Windows Explorer

### ISSUE THREAD

**Issue by DelgLe** [Mechanical-Advantage/AdvantageScope#205]
**Describe the bug**

I just downloaded the beta. I went to try to open a file I had downloaded locally from my one drive. As soon as I opened the folder containing the log files and hoot files that I wanted to open it crashed, and from then, after navigating to that folder, it automatically crashed on opening file explorer from 'Open Logs'
 
**To Reproduce**

1. Start App
2. Click file
3. Click Open Logs
4. As soon as file explorer is opened Advantage Scope crashes

**Expected behavior**
I would be able to open a log file from a folder.

**Screenshots**

![image](https://github.com/user-attachments/assets/f3ecf8ae-f246-4b05-a65c-6146cc8d534f)

**Version (required):**
Copy the contents of the "About AdvantageScope" window and paste it here. On Windows/Linux, click "Help" > "About AdvantageScope". On macOS, click "AdvantageScope" > "About AdvantageScope" in the menu bar.

Version: 4.0.0-beta-1
Distributor: FRC 6328
Platform: win32-x64
Build Date: 9/26/2024, 24:41:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Additional context**

I'm using my work laptop at the moment. 
'Add new logs' has the same behavior.

**Comment by jwbonner** [comment]
In order to debug this, it would be helpful to see the console output from AdvantageScope. You'll need to run it from the command line. If it's installed in the default user location, you should be able to launch it by running:

```
%userprofile%\AppData\Local\Programs\advantagescope\AdvantageScope.exe
```

After attempting to open a file, there will hopefully be a message printed to the console with more details.

**Comment by jwbonner** [comment]
We haven't been able to recreate this, so I'm closing the issue for now. Feel free to reopen if you have a console log or can consistently recreate it on other devices.
