### ISSUE TITLE
Tuner Mode Not showing Editable Number Fields

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#206]
When entering tuning mode, with the button next to the search bar, I can edit boolean values by clicking on the red/green indicator. But there are no text boxes to override number values.

![image](https://github.com/user-attachments/assets/4d8583a1-04e3-4ff7-83a4-c52959bafd47)

**Comment by jwbonner** [comment]
Fields published by AdvantageKit are output-only, so tuning is disabled for them. You should be able to tune any of the fields under a different table like "SmartDashboard". The fact that booleans published by AdvantageKit were still tunable is actually a bug, which I just pushed a fix for. I also added a note to the documentation clarifying that AdvantageKit fields are not tunable.
