### ISSUE TITLE
Integrated data: Add view of current numeric total

### ISSUE THREAD

**Issue by jamesdooley4** [Mechanical-Advantage/AdvantageScope#208]
**Is your feature request related to a problem? Please describe.**
When using the new Integrated view in Line Graph, it's not possible to see the current integrated total exact value.

**Describe the solution you'd like**
Add the current integrated total value as a number in the Left or Right axis details view, either replace or next to the existing view of the current measured value (10) in the picture here:
![image](https://github.com/user-attachments/assets/cdc28e97-0929-4945-9a94-5a623ad18316)

**Describe alternatives you've considered**
Currently I eyeball the value using the graph view, but that often isn't very precise

**Additional context**
Nothing else

**Comment by jwbonner** [comment]
The value displayed under the axis is the integrated value at whatever time is selected or hovered on the graph. Is there something else you're looking for?

**Comment by jamesdooley4** [comment]
When opening a new file today, it does seem to be worked as described. I'll play with it to see what I was doing to get it into the broken state.
