### ISSUE TITLE
Component position offsets not affecting model

### ISSUE THREAD

**Issue by DanPeled** [Mechanical-Advantage/AdvantageScope#210]
**Describe the bug**
When changing the the position offset on a custom robot model's component, the position in the field of the component isnt being affected 

**Version (required):**
Version: 4.0.0-beta-1
Distributor: FRC 6328
Platform: linux-x64
Build Date: 9/26/2024, 24:41:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment]
Are you following the setup process [here](https://docs.advantagescope.org/more-features/custom-assets#setup-process)? The `zeroedRotations` and `zeroedPosition` keys don't affect the component positions unless a component pose is published.

**Comment by DanPeled** [comment]
Oh, I figured it might be something like that, thanks!
