### ISSUE TITLE
3d viewer robot rotation does not align with simulation

### ISSUE THREAD

**Issue by gerth2** [Mechanical-Advantage/AdvantageScope#22]
https://user-images.githubusercontent.com/4583662/208266877-2a65a343-95fc-4d67-8059-9ce3a7ede597.mp4

Looks like a potential units issue? Radians vs. degrees? the pose in NT is broadcasting as degrees, but in AdvantageScope it might be interpreting as radians?

Field2D broadcasts in Degrees for sure, and that's what the sim GUI seems to like:

![image](https://user-images.githubusercontent.com/4583662/208266987-05ac3ef7-9bab-4ab9-81c1-c56f1f1eb6f7.png)

**Comment by jwbonner** [comment]
Yes, this is definitely a units issue. Right now the rotation units are configuration for the odometry tab, but the 3D field always uses radians. I'm hoping to release the next beta sometime this week, which will make this configurable along with a bunch of other improvements:

<img width="1052" alt="3D field config" src="https://user-images.githubusercontent.com/47046556/208267192-2b198b6c-dc41-45f0-b13d-cf69037c7555.png">

**Comment by jwbonner** [comment]
The rotation units are now configurable in [v2.0.0-beta-2](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v2.0.0-beta-2). Under "Config" > "Units" select "degrees."
