### ISSUE TITLE
Google Drive or Dropbox sync support.

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#221]
It would be WONDERFUL if we could have an option that puts log files onto a drive folder to be shared across a team. These could be organized by directories named with github branch names, for example, event_firstchance or just based on the time.  Right now its hard to distribute log files amongst multiple software students and mentors that all want access as soon as a match is over to debug and test.

You could possibly add a google drive or dropbox api key setting.

**Comment by blaze-developer** [comment]
Well, at least for my team we only connect to the robot in the pits with USB or Ethernet, which still allows for internet access simultaneously. I see your point though. Maybe it could save logs into a folder and then either wait for an Internet connection, or manually sync it once you are connected

**Comment by jwbonner** [comment]
After further discussion, we don't think that this needs to be a feature distinct from #202. Users would be free to use a cloud syncing tool of their choice to automatically upload log files downloaded by AdvantageScope, which will be both more reliable and more customizable than including the functionality in AdvantageScope.
