### ISSUE TITLE
Logs fail to load when opening from file browser

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#222]
Log files are correlated with AdvatangeScope, and show an "Open With AdvantageScope" option, however currently in my experience on Windows 11 and Linux, it opens AdvantageScope but not the log file. It'd be nice to be able to have the built in OS option integrate :)

**Comment by jwbonner** [comment]
In this instance it sounds like there’s a bug when opening the files (since this is already supported), but also see https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/359 with regard to the WPILib version on Windows.
