### ISSUE TITLE
Add option to make new fields out of existing ones

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#227]
For example. we have multiple subsystems that log whether they reached their setpoint. If we want to see whether all subsystems reached their setpoint, we have to log another field from the code (and wait for it to deploy). It'd be nice to be able to create new fields inside AdvantageScope, maybe with custom TypeScript code.

**Comment by jwbonner** [comment]
Creating custom fields could encompass an enormous amount of complexity. Beyond just simple math, it could quickly extend to filtering multiple samples, doing geometry operations, and other complex logic. I'm not opposed to adding small additions like #226 (and maybe basic filtering/smoothing options similar to the integration/differentiation options), but more complexity than that is probably out of scope for AdvantageScope. AdvantageKit is really our intended solution for any type of complex analysis.
