### ISSUE TITLE
Feature suggestion: select all when downloading robot logs

### ISSUE THREAD

**Issue by We-Gold** [Mechanical-Advantage/AdvantageScope#23]
It's great that advantagescope has the ability to download log files from the robot, however we often find ourselves downloading many at a time, and it can take unnecessary time to select all of them. I find myself reaching for the datalogtool for downloading for this reason.

It would be great to see this feature, and maybe even more information about the downloading process (estimated time remaining, etc.)

**Comment by jwbonner** [comment]
If you weren't aware, you can select multiple files quickly using shift-click (the same as most file browsers):

![open-file-3](https://user-images.githubusercontent.com/47046556/208757686-5f13743b-f8a0-4ba5-a830-d8906086b014.gif)

Showing the download progress and other info should be a relatively easy addition. I'll see what I can do.

**Comment by We-Gold** [comment]
I saw the shift click, but my brain went to ctrl/cmd + a immediately. Shift clicking is probably enough, but ctrl a could be nice too.

**Comment by jwbonner** [comment]
These improvements are now added in [v2.0.0-beta-2](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v2.0.0-beta-2). I implemented the ctrl/cmd + A shortcut, plus some other quality of life improvements:

![open-file-4](https://user-images.githubusercontent.com/47046556/209231622-314a192d-f659-4052-b430-fe71cf0f0d08.gif)
