### ISSUE TITLE
RLOG Questions

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#230]
I noticed that in your team's 2024 robot code, you use an RLOG server for publishing data. However beforehand I remember RLOG being an old format that shouldn't be used anymore. Are there any advantages to RLOG over NT?

Thanks :3

**Comment by jwbonner** [comment]
RLOG files are not supported by AdvantageKit, but RLOG live streaming is supported as an alternative to NetworkTables. Our recommendation to all teams is to use NetworkTables for live streaming. RLOG streaming currently had stability issues and we do not expect to change our recommendation to teams in the foreseeable future, especially as NetworkTables continues to improve in future WPILib releases.

**Comment by blaze-developer** [comment]
Interesting, was there a problem with NT that you were attempting to solve with RLOG streaming?

**Comment by jwbonner** [comment]
NetworkTables 4 has had stability issues over the past few years in certain circumstances. Most of those have been ironed out by now, but we implemented an updated version of RLOG as a backup. But again, it will almost certainly be less stable than NetworkTables for most users and we don't plan on providing support for it.
