### ISSUE TITLE
README and documentation tiny problems

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#234]
Scroll to the bottom of the readme under assets section. This aswell as on the line graph page in the new docs, the arrow to the right to go to the next tab is the wrong emoji.

**Comment by jwbonner** [comment]
Thanks, I fixed the link in the README. The emoji on the line graph page looks right to me, it's a map icon that matches the odometry tab. Emoji rendering is dependent on operating system, so is it possible that your OS doesn't support that icon?

<img width="578" alt="Screenshot 2024-10-18 at 10 44 44 AM" src="https://github.com/user-attachments/assets/ff36340e-2e17-433e-ba15-12c95d3b647c">

**Comment by blaze-developer** [comment]
I meant the blue arrow emoji on that tab is a different emoji than the others. Perhaps my noto fonts make it more obvious than your fonts.

**Comment by jwbonner** [comment]
I've confirmed that the right arrow uses exactly the same unicode symbol on several tabs. Can you send a screenshot of what you're seeing?

**Comment by blaze-developer** [comment]
I meant the blue arrow emoji on that tab is a different emoji than the others. Perhaps my noto fonts make it more obvious than your fonts. It appears as a yellow boxed arrow and not a blue arrow on a chromeOS laptop and not any of my other devices.

**Comment by blaze-developer** [comment]
![image](https://github.com/user-attachments/assets/65d9ca4f-c147-4cb9-aff7-ed3822cb0fd6)

**Comment by blaze-developer** [comment]
This renders correctly on other tabs, it seems to be only that one.
![image](https://github.com/user-attachments/assets/5d12cdf5-2a19-4d21-8511-2f762eec829a)

**Comment by jwbonner** [comment]
I don't think there's anything I can do about a browser that is failing to render the page as served. The styling of those pages is identical, and changing the styling for a single page is nontrivial even if I wanted to do so. I don't see any evidence of an issue with the page itself, so I'm going to close this issue.
