### ISSUE TITLE
Can't see PathPlanner fields while in "NT4+AdvantageKit" mode

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#237]

**Comment by jwbonner** [comment]
AdvantageKit is designed to expect that all telemetry will use AdvantageKit logging. In addition to the issue you've observed, PathPlanner telemetry by default will not be included in AdvantageKit logs files. I would recommend using the custom logging callbacks in PathPlanner to send telemetry to AdvantageKit. The swerve example project for AdvantageKit shows how to do this ([link](https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/example_projects/swerve_drive/src/main/java/frc/robot/subsystems/drive/Drive.java#L92-L100)).

**Comment by katzuv** [comment]
I see, thank you!
