### ISSUE TITLE
Statistics Tab Values not Reconnecting

### ISSUE THREAD

**Issue by JosephTLockwood** [Mechanical-Advantage/AdvantageScope#238]
**Describe the bug**
When you rerun sim code, statistics fields that were previously being displayed no longer appear

**To Reproduce**

1. Run code in sim
2. Display a value in the Statistics tab
3. Rerun code
4. Values no longer are displayed

**Expected behavior**
When you deploy code or rerun in the sim, values should auto-reconnect.

**Screenshots**
<img width="818" alt="image" src="https://github.com/user-attachments/assets/939717c4-2760-4b01-bb22-a391f5ecba38">

**Version (required):**
Version: 4.0.0-beta-2
Distributor: FRC 6328
Platform: win32-x64
Build Date: 10/19/2024, 02:29:37 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Additional context**
This also appears to break other tabs as well after failed connection.

**Comment by jwbonner** [comment]
It looks like there were a couple of edge cases where statistics calculations would fail and crash the renderer loop. I pushed a fix which should address those issues.
