### ISSUE TITLE
Time slider not working while (Searching)

### ISSUE THREAD

**Issue by itsmichaelyu** [Mechanical-Advantage/AdvantageScope#24]
In the Odometry and Swerve tabs, the time slider isn't working for me, but in the Joystick tab I am able to slide the time around and then play it. This is on the latest beta

**Comment by jwbonner** [comment]
This should be fixed in cc48003. There was an edge case when a live source disconnected which caused the timeline controls to remain disabled on any existing tabs. New tabs created after the disconnect would work properly though.
