### ISSUE TITLE
"Check for Update" goes to stable version even while on beta

### ISSUE THREAD

**Issue by amsam0** [Mechanical-Advantage/AdvantageScope#241]
**Describe the bug**
When using the Check for Update button on a beta, AdvantageScope will correctly recognize that there is a new beta available. However, when you click on download, it will go to https://github.com/Mechanical-Advantage/AdvantageScope/releases/latest, which ignores pre-releases and shows v3.2.1 (the latest non-prerelease).

**To Reproduce**

1. On macOS, go into the AdvantageScope menu in the menu bar. Not sure where the Check for Update button is on Windows and Linux.
2. Click Check for Update
3. Click Download
4. See that it opens v3.2.1 instead of the beta

**Expected behavior**
Beta release is shown

**Version (required):**
Version: 4.0.0-beta-1
Distributor: FRC 6328
Platform: darwin-arm64
Build Date: 9/26/2024, 24:41:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment]
Thanks for reporting! This is actually one of the fixes that's part of the second beta release, so it should link to the correct page when you upgrade to the _third_ release.
