### ISSUE TITLE
Highlight search results in the console tab

### ISSUE THREAD

**Issue by katzuv** [Mechanical-Advantage/AdvantageScope#244]

**Comment by jwbonner** [comment]
Can you elaborate? The console tab already includes a filter option, and there is also a search option for fields. The issue template asks you to answer these questions:

* Is your feature request related to a problem? Please describe.
* Describe the solution you'd like
* Describe alternatives you've considered

**Comment by katzuv** [comment]
Yes sorry, I just though I was clear. I mean to highlight the exact string searched for in the results, so it will be easier to find the text in large lines. So if I search e.g. for "navX":
![example~2.png](https://github.com/user-attachments/assets/d4c6e428-d884-470f-8cce-ce5ccef4e3ea)
