### ISSUE TITLE
Support conversion of Hoot files on macOS

### ISSUE THREAD

**Issue by ArchdukeTim** [Mechanical-Advantage/AdvantageScope#246]
CTRE has released a Tuner X app for macOS, as well as 'owlet', https://docs.ctr-electronics.com/cli-tools, a tool for converting hoot files on the command line. Should be trivial to add support for downloading hoot files and converting them on macOS

**Comment by jwbonner** [comment]
We implemented this feature recently and it is fully functional. We have been communicating with CTRE regarding this feature but are still working through some legal questions. I can't provide a timeline for when we might release it.

**Comment by jwbonner** [comment]
See #232
