### ISSUE TITLE
Only 3 of 6 Xbox Controller Axis are being added to the wpilog

### ISSUE THREAD

**Issue by hadley31** [Mechanical-Advantage/AdvantageScope#25]
When I am connected to the simulator, the joystick page picks up all 6 Xbox Controller axis correctly and displays them on the xbox controller. 

However, if I then open the log file generated from AdvantageKit, only 3 of them show up in AdvantageScope and have the following mapping:  

0. Left Stick Y
1. Left Trigger
2. Right Stick X

OS: Windows
WPILib: 2023 Beta 6
AdvantageKit: 2.0.0-beta-2
AdvantageScope: 2.0.0-beta-1

**Comment by jwbonner** [comment]
Turns out this is an issue with AdvantageScope; the WPILOG decoder was skipping every other value in float arrays. This is now fixed by 2b2d02e
