### ISSUE TITLE
cannot add third-party robot models due to content security policy

### ISSUE THREAD

**Issue by gcschmit** [Mechanical-Advantage/AdvantageScope#26]
With Advantage Scope 2.0.0-beta-2 on macOS 13.1, after attempting to add json and glb files for our team's robot, the robot was added to the robot menu in the 3D Field tab, but the robot was not displayed and the following error was generated:

> Refused to connect to 'blob:<URL>' because it violates the following Content Security Policy directive: "connect-src ws: wss: file:".
> 
> hub.js:47434 Refused to connect to 'blob:file:///7ce359aa-faba-4219-b356-fe82a252c279' because it violates the following Content Security Policy directive: "connect-src ws: wss: file:".

Content Security Policies are definitely not my area of expertise, but, based on a couple StackOverflow posts, I updated hub.html and satellite.html to specify blob as an additional connect source:

`content="default-src 'self'; script-src 'self'; connect-src ws: wss: file: blob:"`

(I'm not sure if satellite needed to be changed or not.) After building locally and running the app copied from the built DMG, the robot model was displayed and no errors were observed in the console.

**Comment by jwbonner** [comment]
This should be fixed. I updated both "hub.html" and "satellite.html". Changing the satellite is necessary because each window has its own render process that loads the model independently.
