### ISSUE TITLE
Keyboard Combination for opening tab in new window.

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#262]
Right now there is ALT+ a letter.
It would be awesome if something like SHIFT + ALT + letter would open it in a new tab instead.

**Comment by jwbonner** [comment]
I'm not clear what you're proposing. There are already keyboard shortcuts for opening new tabs and opening pop-up windows (ctrl+shift+T). You can't create pop-up windows without creating new tabs because configuration is always handled from the main window.
