### ISSUE TITLE
Option to force translucency to be on.

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#263]
I use a tiling window compositor on my Linux system, and due to the nature of that, window translucency will always be off due to the program always being contained in a specific space, and perhaps the program *thinking* it's in fullscreen mode. It would be nice if we could have translucency even in fullscreen with an override option. Allowing people to style their experience how they would like :) No big deal, just a little thing I think would be interesting. If you didn't want to add an option the the built-in settings menu, even just having a configuration file for kind-of hidden settings would work as well.

**Comment by jwbonner** [comment]
AdvantageScope doesn't support translucency on Linux regardless of the window manager, and was also disabled on Windows in beta 2 because of an Electron bug. Currently it is only supported on macOS.

**Comment by jwbonner** [comment]
As explained, translucency is only supported on macOS (this is an OS/Electron limitation on other platforms).
