### ISSUE TITLE
Struct decoding breaks in sim with error "Fixed length arrays are unimplemented"

### ISSUE THREAD

**Issue by TheComputer314** [Mechanical-Advantage/AdvantageScope#273]
**Describe the bug**
![image](https://github.com/user-attachments/assets/bc735bd2-e878-431f-a6e4-69e4547594f5)
The above error message appears when connecting to a sim robot over NT, breaking all struct decoding. Log files are unaffected.

**To Reproduce**

1. Open a robot sim with photonvision simulation.
2. Connect to the simulator.

**Expected behavior**
For struct decoding to not break.

**Version (required):**
Version: 4.0.0-beta-3
Distributor: FRC 6328
Platform: win32-x64
Build Date: 11/12/2024, 05:08:23 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Additional context**
I suspect the cause is the `.photonvision` NT table?
Tested on https://github.com/icrobotics-team167/2024_Off_Season/tree/WPILib2025

**Comment by TheComputer314** [comment]
Unsure if this is Photon's fault or AScope's fault so putting this in both repos.

**Comment by jwbonner** [comment]
I think you should be able to temporarily work around this issue by avoiding publishing struct types that include arrays (specifically `OdometryFrame` seems to be the issue here).
