### ISSUE TITLE
Docs Sentence Error In Live Tuning Section

### ISSUE THREAD

**Issue by Jon-Zimmerman** [Mechanical-Advantage/AdvantageScope#282]
On the docs site at [https://docs.advantagescope.org/getting-started/connect-live/#tuning-with-advantagekit](url) there is a sentence error with a duplicate word.
"will appear under the "Tuning" table **when when** using the "

Code location:
https://github.com/Mechanical-Advantage/AdvantageScope/blob/26ed5936f6ea875752889e9405886646166ce6b4/docsSite/docs/getting-started/connect-live.md?plain=1#L80C253-L80C309

**Comment by jwbonner** [comment]
Thanks for the catch!
