### ISSUE TITLE
Closing out of the export popup without exporting causes "Export in Progress" to pop up if you attempt to export again

### ISSUE THREAD

**Issue by Gold856** [Mechanical-Advantage/AdvantageScope#289]
**Describe the bug**
If you open the export window, and decide you don't want to export anything and decide to close the export window, but you then try to open the export window again, AdvantageScope will error, saying an export is in progress, even though you never started an export.

**To Reproduce**

1. Click on `File > Export Data`.
2. Close the popup.
3. Repeat step 1.
4. Observe an "Export in Progress" error.

**Expected behavior**
AdvantageScope should not report that an export is in progress.

**Version (required):**
Version: 4.0.0-beta-2
Distributor: WPILib
Platform: win32-x64
Build Date: 11/6/2024, 21:44:18 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment]
Thanks for catching that. It properly handled the case of the "X" button in the window being clicked, but not the system-level window close button (which is OS specific and not always present).
