### ISSUE TITLE
Feature Request - Draw Arbitrary Trajectory on Odometry View

### ISSUE THREAD

**Issue by tervay** [Mechanical-Advantage/AdvantageScope#31]
We'd like to generate trajectories on the fly, and viewing them would be easiest if we were able to plot a trajectory on the odometry view. This is possible in Glass, but AdvScope is much more integrated into our workflow.

**Comment by tervay** [comment]
![image](https://user-images.githubusercontent.com/7595639/212562981-0bf3a6af-e521-44f5-b034-bf4731c891c3.png)

Oops.

**Comment by jwbonner** [comment]
Plotting a trajectory is supported in both the odometry and 3D views. Just log a series of poses for the waypoints (AdvantageKit has a `recordOutput()` method that takes a trajectory) and change the type of object from "Robot" to "Trajectory".
