### ISSUE TITLE
Odometry visualizations rotate far too fast

### ISSUE THREAD

**Issue by JulianOrteil** [Mechanical-Advantage/AdvantageScope#34]
GIF for convenience displaying output from AdvantageScope, Glass, a simulated NavX's reported angle, and the current controller input:

![TooMuchSpin](https://user-images.githubusercontent.com/23083317/213353392-fd31f9cd-30f0-4db2-972b-675410f80116.gif)

I wouldn't want to go on this carnival ride!

**Comment by jwbonner** [comment]
I suspect your rotation units for the odometry view are set to radians and not degrees. You can change it under "Coordinate System" at the bottom of the odometry tab.

**Comment by JulianOrteil** [comment]
Yep, that was it. Much appreciated.
