### ISSUE TITLE
Custom robot 3D model

### ISSUE THREAD

**Issue by CrispyBacon1999** [Mechanical-Advantage/AdvantageScope#35]
Is there a way to use a custom robot model without rebuilding the entire project? We're using AdvantageScope quite a lot this year and would like to be able to represent our robot a little bit better, but it doesn't look like there's a way to do it without putting the model in the frcData folder and building it locally.

**Comment by jwbonner** [comment]
Yes, this is supported.. In AdvantageScope's menu bar go to "Help" > "Show FRC Data Folder..." You can put extra models here (with the appropriate naming and JSON file), and they'll be loaded when the app launches.

**Comment by CrispyBacon1999** [comment]
Ooh, that's awesome! Thanks for the quick response!
