### ISSUE TITLE
Probable bug

### ISSUE THREAD

**Issue by srimanachanta** [Mechanical-Advantage/AdvantageScope#45]
Working on a PR, and noticed this. `toString` shouldn't have a parameter.

https://github.com/Mechanical-Advantage/AdvantageScope/blob/6f0e2c02305c4083b7451f43d1e6419a25f3d9a2/src/hub/dataSources/nt4/msgpack.js#L507

**Comment by jwbonner** [comment]
The parameter changes the base of the number (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString)), which seems to be used here to display the byte in hexadecimal.
