### ISSUE TITLE
Layout glitch: April tag Locations off when on Red Alliance

### ISSUE THREAD

**Issue by randomstring** [Mechanical-Advantage/AdvantageScope#49]
<img width="667" alt="Screenshot 2023-02-16 at 1 13 31 PM" src="https://user-images.githubusercontent.com/1033976/219489314-53286547-f561-463a-9144-6623be5a5cb4.png">

When on the red alliance and using the WPILib to change the layout origin, the april tags are off by a bit. Front AprilTag is what AdvantageScope is showing, the smiley face AprilTag is the 3dPose of the transformed apriltag computed by WPIlib `AprilTagFieldLayout.setOrigin()`

```        
  layout.setOrigin(OriginPosition.kRedAllianceWallRightSide);
  Logger.getInstance().recordOutput("Vision/3d_AprilTags/1", layout.getTagPose(1).get());
```

The reported AprilTag 3dPose is [0.9456419999999985,7.157973999999999,0.462788,1,0,0,6.123233995736766e-17]
(functionally equivalent to  [0.945642,7.157974,0.462788,1,0,0,0])

I'm wondering where the error is coming from? Is it in the AdvantageScope 3d map?

**Comment by randomstring** [comment]
So the field layout config file lists the field dimensions as:
```json
      "length": 16.4592, 
      "width": 8.2296
```

The game manual says the length field is 54 ft. 3 1⁄4 in or 651.25" or 16.54175 meters. A difference of 3.25"
field width is 315.5" or 8.0137 meters. off by 8.5". Maybe we missed an update somewhere.

**Comment by jwbonner** [comment]
Where are you getting that config JSON? I see 16.54175 meters in WPILib and it hasn't been updated since January 8th when the PR was merged: https://github.com/wpilibsuite/allwpilib/blob/main/apriltag/src/main/native/resources/edu/wpi/first/apriltag/2023-chargedup.json#L149

AdvantageScope uses 651.25 inches: https://github.com/Mechanical-Advantage/AdvantageScope/blob/main/frcData/Field3d_2023.json#L7

**Comment by jwbonner** [comment]
Here's what I see with a red alliance origin on WPILib 2023.3.2 (loaded with `AprilTagFields.k2023ChargedUp.loadAprilTagLayoutField()`) and AdvantageScope 2.2.1:

<img width="551" alt="Screen Shot 2023-02-16 at 4 47 10 PM" src="https://user-images.githubusercontent.com/47046556/219494370-430c09db-e2fb-43e4-a90b-e7c9084316a9.png">

**Comment by randomstring** [comment]
Thanks. We had an old (or just wrong?) version of the field setup.

for those who come after, load the field data this way and not from your own file.

```
AprilTagFields.k2023ChargedUp.loadAprilTagFieldLayout();
```
