### ISSUE TITLE
Line graph issues with very small values

### ISSUE THREAD

**Issue by lobsterwise** [Mechanical-Advantage/AdvantageScope#50]
If you are plotting a value on the line graph that is very small, you will start to have problems with the automatic vertical zoom. You can see this when plotting for example a value with a single pole filter. If you don't round it somewhere, it will eventually reach the double minimum limit and the entire program will freeze.

**Comment by jwbonner** [comment]
Thanks, this should be fixed in [v2.2.2](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v2.2.2) with ac3720b. That change should also fix the same issue occurring for very large values.
