### ISSUE TITLE
DS log current issue

### ISSUE THREAD

**Issue by TylerSeiford** [Mechanical-Advantage/AdvantageScope#51]
When viewing a log from our robot, PDH channel 18 shows 0 current draw.  Here's a comparison of the default viewer and advantage scope.

![image](https://user-images.githubusercontent.com/50031864/219969357-dbc620f8-d622-48e5-ad13-750560d77d08.png)

![image](https://user-images.githubusercontent.com/50031864/219969388-0c02fe04-b991-41c4-97e7-8a15bf11b5c5.png)

[2023_02_19 12_44_12 Sun.zip](https://github.com/Mechanical-Advantage/AdvantageScope/files/10777683/2023_02_19.12_44_12.Sun.zip)

**Comment by TylerSeiford** [comment]
Channels 15, 16 & 17 (the rest of our drive train) all show correctly.

**Comment by rzblue** [comment]
Just wanted to chime in here- I don't think AdvantageScope is reading the DS log currents correctly (at least not with the PDH).

 Here are two screenshots from the same log, one in DS Log viewer, one in advantagescope. I've isolated channel 19 as that seems to be the one that most noticable has this issue in our logs. The images are zoomed in on the same 7 second period, the first 7 seconds of auto at the start of one of our matches.
 
 In advantagescope, the current draw value is always a discrete value - 0, 32, 64, or 96. The DS Log viewer shows the accurate (and more believable) reading.
 
 
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/13878527/224195454-34581a8c-51df-4fbc-accb-d55690f76b87.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/13878527/224195641-0e9253e9-6695-4056-8d9f-a3fb6fa15816.png">

**Comment by jwbonner** [comment]
This should now be fixed (d6b0569). As far as I can tell, this was only an issue with the PDH and not the PDP. For comparison, here's what the two logs posted here look like after the fix:

@TylerSeiford

<img width="817" alt="Screenshot 2023-10-15 at 7 37 32 PM" src="https://github.com/Mechanical-Advantage/AdvantageScope/assets/47046556/107ebab6-23a7-45a9-8f83-dd3993c0da6e">

@rzblue

<img width="815" alt="Screenshot 2023-10-15 at 7 42 53 PM" src="https://github.com/Mechanical-Advantage/AdvantageScope/assets/47046556/057b0776-3565-4739-b808-5fab0289a4ed">
