### ISSUE TITLE
Decode workers are created but never killed?

### ISSUE THREAD

**Issue by jonahsnider** [Mechanical-Advantage/AdvantageScope#6]
It seems like the decode workers are created each time a connection is initialized, but they are never killed. This (probably) is not good as it wastes computer resources during long debug sessions where you may reconnect many times.
You can observe this behavior by opening the devtools and then using a keybind to repeatedly connect to a robot/sim. You can see all the worker threads in the "Sources" tab:

![The "Sources" tab of the devtools window](https://user-images.githubusercontent.com/7608555/159186865-24eb9a57-af58-45ec-9477-7caf392f6c0b.png)

Can a single decode worker be created once and reused between connections?

**Comment by jonahb55** [comment]
This issue is now fixed (c75f384) by creating each worker once on init and reusing them. See my comment on #7 as well. I'll make a new release soon to include this fix.
