### ISSUE TITLE
NT 4 Mode (w/o AdvantageKit) still subscribes to all topics

### ISSUE THREAD

**Issue by jlmcmchl** [Mechanical-Advantage/AdvantageScope#67]
When in the shop on Monday, I noticed that AdvantageScope managed to consume 15GB of data in a short window. When I switched over to NT4 mode  w/ AdvantageKit, I did not see this behavior.

**Comment by jwbonner** [comment]
Have you been able to recreate this since? I'm not seeing the issue on AdvantageScope v2.3.0 (confirming NT subscriptions using outline viewer).

**Comment by jwbonner** [comment]
I'm closing this issue for now since it don't appear to be occurring on the latest version of AdvantageScope. If you see this again feel free to reopen.
