### ISSUE TITLE
AppImage Releases

### ISSUE THREAD

**Issue by max-niederman** [Mechanical-Advantage/AdvantageScope#78]
AppImage releases would make it much easier to run AdvantageScope on distros which aren't specifically supported. For example, I'd like to run AdvantageScope on NixOS, but it's extremely difficult to package Electron apps there (because electron is just kinda a pain). The build tool AdvantageScope uses, `electron-builder` does support AppImage builds, so it would probably be easy to do.

**Comment by jwbonner** [comment]
Fixed by https://github.com/Mechanical-Advantage/AdvantageScope/pull/80
