### ISSUE TITLE
Connecting to simulator running WPILib 2024 beta 1 crashes robot code

### ISSUE THREAD

**Issue by mjansen4857** [Mechanical-Advantage/AdvantageScope#97]
**Describe the bug**
When attempting to connect to a simulator running WPILib 2024 beta 1, the robot code will crash. Connection works fine if the project runs WPILib 2023.

**To Reproduce**
1. Create new 2024 robot code project
2. Launch simulator
3. Attempt to connect to simulator in AdvantageScope
4. Simulator crashes

**Version:**
* AdvantageScope 3.0.0-beta-1
* WPILib 2024.1.1-beta-1
* Windows 11

**Console output**
```
********** Robot program starting **********
NT: Listening on NT3 port 1735, NT4 port 5810
********** Robot program startup complete **********
NT: Got a NT4 connection from 127.0.0.1 port 59767
NT: CONNECTED NT4 client 'AdvantageScope@1' (from 127.0.0.1:59767)
NT: Got a NT4 connection from 127.0.0.1 port 59768
NT: CONNECTED RTT client (from 127.0.0.1:59768)
NT: DISCONNECTED NT4 client 'AdvantageScope@1' (from 127.0.0.1:59767): stream error: EAGAIN
NT: NT4 socket error: resource temporarily unavailable

> Task :simulateJavaRelease FAILED
```

**Comment by jwbonner** [comment]
This appears to be a bug with ntcore after switching to a new protocol revision for 2024, since the same issue occurs with other NT clients. https://github.com/wpilibsuite/allwpilib/issues/5781
