### ISSUE TITLE
Document all supported datatypes

### ISSUE THREAD

**Issue by lidor51** [Mechanical-Advantage/AdvantageScope#98]
Add to your repo a documentation page of all supported data types.

**Comment by jwbonner** [comment]
The documentation pages for most tabs include a list of supported data types and formats, and all others support any valid type that can be published through NT/WPILOG (e.g. the table tab). Documenting the set of supported structs is addressed in this WPILib issue: https://github.com/wpilibsuite/allwpilib/issues/6058. I don't think there are any additional details that need to be included in AdvantageScope's docs.
